# Create VTP transparent mode
---
- name: Configuring devices
  hosts: all
  gather_facts: false
  
  vars: # Variável de conexão
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: teste
    ansible_ssh_pass: teste

  tasks:
    - name: Configurando VTP Transparent mode e NTP em todos os switches 
      ios_config: # Módulo de configuração       
        lines:
          - vtp domain ansible
          - vtp mode transparent         
        
      register: print_output # Armazenando os dados executados no módulo acima

    -  debug: var=print_output.stdout_lines # Imprimindo os dados armazenados 

# Create VLANS
    - name: Criando VLANS 10, 20, 30 e 40
      ios_vlan:
        aggregate:
          - vlan_id: 10              
            name: VLAN 10          
            state: active

          - vlan_id: 20              
            name: VLAN 20          
            state: active 

          - vlan_id: 30              
            name: VLAN 30          
            state: active

          - vlan_id: 40              
            name: VLAN 40          
            state: active          
          
      register: print_output

# 802.1q nas interfaces
- name: Configuring 802.1q in the interfaces in core switches
  hosts: ansible_core
  gather_facts: false

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: teste
    ansible_ssh_pass: teste

  tasks:    
    - name: Habilitando 802.1q nas interfaces dos switches core
      ios_config:        
        parents: "interface {{ item.interface }}"
        lines:
          - switchport trunk encapsulation dot1q
      with_items:
        - { interface : Ethernet0/0 }
        - { interface : Ethernet0/1 }
        - { interface : Ethernet0/2 }
        - { interface : Ethernet0/3 }      

      register: print_output   

    - name: HABILITANDO TRUNK MODE NAS INTERFACES ATIVAS DOS SWITCHES CORE
      ios_l2_interface:
        aggregate:
          - name: Ethernet0/0
            mode: trunk
            trunk_allowed_vlans: 1-4094
          - name: Ethernet0/1
            mode: trunk
            trunk_allowed_vlans: 1-4094
          - name: Ethernet0/2
            mode: trunk
            trunk_allowed_vlans: 1-4094
          - name: Ethernet0/3
            mode: trunk
            trunk_allowed_vlans: 1-4094

      register: print_output   

# 802.1q nas interfaces
- name: Configuring 802.1q in the interfaces in access switches
  hosts: ansible_access
  gather_facts: false

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: teste
    ansible_ssh_pass: teste

  tasks:    
    - name: Habilitando 802.1q nas interfaces dos switches access
      ios_config:        
        parents: "interface {{ item.interface }}"
        lines:
          - switchport trunk encapsulation dot1q
      with_items:
        - { interface : Ethernet1/0 }
        - { interface : Ethernet1/1 }  

      register: print_output

      - name: HABILITANDO TRUNK MODE NAS INTERFACES ATIVAS DOS SWITCHES ACCESS
      ios_l2_interface:
        aggregate:
          - name: Ethernet1/0
            mode: trunk
            trunk_allowed_vlans: 1-4094
          - name: Ethernet1/1
            mode: trunk
            trunk_allowed_vlans: 1-4094          
            
      register: print_output

#Configuring HSRP group 1 in the SW_CORE_1
- name: Configuring switch virtual interface with HSRP in the Core SW_CORE_1
  hosts: SW_CORE_1
  gather_facts: false

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: teste
    ansible_ssh_pass: teste

  tasks:    
    - name: Configurando switch virtual interface com HSRP grupo 1 no SW_CORE_1
      ios_config:        
        parents: "interface {{ item.interface }}"
        lines:
          - "ip address {{ item.address }} {{ item.mask }}" 
          - "no shutdown"

          - "standby 1 ip 192.168.11.3"
          - "standby 1 preempt"
          - "standby 1 priority 120"

          - "standby 1 ip 192.168.11.67"
          - "standby 1 preempt"
          - "standby 1 priority 120"

          - "standby 1 ip 192.168.11.131"
          - "standby 1 preempt"
          - "standby 1 priority 120"

          - "standby 1 ip 192.168.11.195"
          - "standby 1 preempt"
          - "standby 1 priority 120"
          
      with_items:
        - { interface : vlan 10, address : 192.168.11.1, mask : 255.255.255.192 }
        - { interface : vlan 20, address : 192.168.11.65, mask : 255.255.255.192 }
        - { interface : vlan 30, address : 192.168.11.129, mask : 255.255.255.192 }
        - { interface : vlan 40, address : 192.168.11.193, mask : 255.255.255.192 }

      register: print_output

    #Configuring HSRP group 2 in the SW_CORE_1
    - name: Configurando switch virtual interface com HSRP grupo 2 no SW_CORE_1
      ios_config:        
        parents: "interface {{ item.interface }}"
        lines:          
          - "standby 2 ip 192.168.11.4"        
          - "standby 2 preempt"
          - "standby 2 priority 110"

          - "standby 2 ip 192.168.11.68"
          - "standby 2 preempt"
          - "standby 2 priority 110"

          - "standby 2 ip 192.168.11.132"
          - "standby 2 preempt"
          - "standby 2 priority 110"

          - "standby 2 ip 192.168.11.196"
          - "standby 2 preempt"
          - "standby 2 priority 110"

      with_items:
        - { interface : vlan 10 }
        - { interface : vlan 20 }
        - { interface : vlan 30 }
        - { interface : vlan 40 }      

      register: print_output

#Configuring HSRP group 2 in the SW_CORE_2
- name: Configuring switch virtual interface with HSRP Core SW_CORE_2
  hosts: SW_CORE_2
  gather_facts: false

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: teste
    ansible_ssh_pass: teste

  tasks:    
    - name: Configurando switch virtual interface com HSRP grupo 2 no SW_CORE_2
      ios_config:        
        parents: "interface {{ item.interface }}"
        lines:
          - "ip address {{ item.address }} {{ item.mask }}" 
          - "no shutdown"

          - "standby 2 ip 192.168.11.4"   
          - "standby 2 preempt"
          - "standby 2 priority 120"

          - "standby 2 ip 192.168.11.68"
          - "standby 2 preempt"
          - "standby 2 priority 120"

          - "standby 2 ip 192.168.11.132"
          - "standby 2 preempt"
          - "standby 2 priority 120"

          - "standby 2 ip 192.168.11.196"
          - "standby 2 preempt"
          - "standby 2 priority 120"
          
      with_items:
        - { interface : vlan 10, address : 192.168.11.2, mask : 255.255.255.192 }
        - { interface : vlan 20, address : 192.168.11.66, mask : 255.255.255.192 }
        - { interface : vlan 30, address : 192.168.11.130, mask : 255.255.255.192 }
        - { interface : vlan 40, address : 192.168.11.194, mask : 255.255.255.192 }

      register: print_output

    #Configuring HSRP group 1 in the SW_CORE_2
    - name: Configurando switch virtual interface com HSRP grupo 1 no SW_CORE_2
      ios_config:        
        parents: "interface {{ item.interface }}"
        lines:          
          - "standby 1 ip 192.168.11.3"       
          - "standby 1 preempt"
          - "standby 1 priority 110"

          - "standby 1 ip 192.168.11.67"
          - "standby 1 preempt"
          - "standby 1 priority 110"

          - "standby 1 ip 192.168.11.131"
          - "standby 1 preempt"
          - "standby 1 priority 110"

          - "standby 1 ip 192.168.11.195"
          - "standby 1 preempt"
          - "standby 1 priority 110"

      with_items:
        - { interface : vlan 10 }
        - { interface : vlan 20 }
        - { interface : vlan 30 }
        - { interface : vlan 40 }      
        
      register: print_output